### ISSUE TITLE
Inconsistent behaviour of delta_days()

### ISSUE THREAD

**Issue by borekl** [chansen/p5-time-moment#49]
```
~$ cat t.pl
use Time::Moment;
use v5.10;

my $before = Time::Moment->from_string('20121231T235959Z');
my $after  = Time::Moment->from_string('20130101T000000Z');

say 'Years:   ', $before->delta_years($after);
say 'Months:  ', $before->delta_months($after);
say 'Days:    ', $before->delta_days($after);
say 'Hours:   ', $before->delta_hours($after);
say 'Minutes: ', $before->delta_minutes($after);

~$ perl t.pl
Years:   0
Months:  0
Days:    1
Hours:   0
Minutes: 0

```

Why does delta_days method behave differently from the rest of the delta_* methods? Is this intended behavior?

**Comment by chansen** [comment]
Why do you think it’s inconsistent? The difference is one day between `$before` and `$after`. The difference in years and months is in terms of complete units as documented.

**Comment by chansen** [comment]
This could be further clarified in the documentation with a few examples.

**Comment by borekl** [comment]
It says 'complete days' in the documentation, exactly same formulation is used for the rest of the 'delta' methods. Do you want to tell me that between $before and $after one complete day elapsed?

**Comment by chansen** [comment]
The difference in days between the given local dates `20121231`  and `20130101` is one day.

**Comment by mbethke** [comment]
I have to concur with @borekl: if there's any logic in this behavior, I don't get it at all. Consider this program and its output:
```
  use Time::Moment;
  use v5.10;

  my $before = Time::Moment->from_string('20121231T235959Z');

  my $y = $before->plus_years(1);
  my $m = $before->plus_months(1);
  my $d = $before->plus_days(1);
  my $H = $before->plus_hours(1);
  my $M = $before->plus_minutes(1);

  for my $t ( $y, $m, $d, $H, $M ) {
      say "$t: ";
      say "\tYears:   ", $before->delta_years($t);
      say "\tMonths:  ", $before->delta_months($t);
      say "\tDays:    ", $before->delta_days($t);
      say "\tHours:   ", $before->delta_hours($t);
      say "\tMinutes: ", $before->delta_minutes($t);
  }
```

```
2013-12-31T23:59:59Z:
        Years:   1
        Months:  12
        Days:    365
        Hours:   8760
        Minutes: 525600
2013-01-31T23:59:59Z:
        Years:   0
        Months:  1
        Days:    31
        Hours:   744
        Minutes: 44640
2013-01-01T23:59:59Z:
        Years:   0
        Months:  0
        Days:    1
        Hours:   24
        Minutes: 1440
2013-01-01T00:59:59Z:
        Years:   0
        Months:  0
        Days:    1
        Hours:   1
        Minutes: 60
2013-01-01T00:00:59Z:
        Years:   0
        Months:  0
        Days:    1
        Hours:   0
        Minutes: 1
```
Add one year: the difference is a full year, or 12 as expressed in complete months, 365 as expressed in full days, and so on.
Add one month: the resulting year is different, but the *difference* is not a *complete* year, but one month or, being January, 31d and so on.
Add one day: It's not a complete month, even though the resulting month is different, it's only 1d/24h/1440m.

Everything consistent so far. If you add one `$UNIT`, the delta in `$UNITs` is 1. If you add one of the next smaller units, the delta in `$UNITs` is 0.

Add one hour though, and it gets weird. The difference is 1 in hours, but also 1 in days. Adding one minute produces the same weirdness, although *only* on the days and minutes level, not hours.

Looking at the code, I think it makes sense why we're seeing this: `moment_delta_days()` first truncates to integer days and then subtracts those while `THX_moment_delta_hours()` first calculates the difference in seconds and then truncates by integer division by 3600.

**Comment by chansen** [comment]
There is a fundamental difference between calendar units and time units:

**Calendar units** represent positions within the calendar. For instance, moving from “December 31 to January 1” signifies transitioning to the next day, even if only one second has passed.

**Time units**, on the other hand, measure precise durations, quantifying the exact number of seconds, minutes, or hours between two moments.

Using your example:

The difference between 2012-12-31T23:59:59Z and 2013-01-01T00:59:59Z:

- In **calendar terms**, this spans 2 calendar days because crossing one second into January 1 moves to the next day.
- In **time units**, the difference is exactly 1 hour, or 60 minutes.


I hope this provides clarity. The documentation should be updated to better explain the distinctions between calendar and time units.

**Comment by chansen** [comment]
I’ve spent some time working on this documentation and hope the following will help clarify any confusion. Your feedback is greatly appreciated!

---

# Time and Calendar Arithmetic

Time and Calendar Arithmetic refers to operations involving the addition, subtraction, or comparison of temporal values. These operations can involve either **precise time units** (such as seconds, minutes, and hours) or **calendar units** (like days, months, and years). These two types of arithmetic are fundamentally different due to their distinct characteristics.

Mixing **calendar units** and **time units** can lead to confusion and inaccuracies because they adhere to different principles:

## 1. Calendar Units Are Variable
- **Days, months, and years** do not have consistent lengths:
  - A day is generally 24 hours, but events like daylight saving time changes or leap seconds can alter this.
  - A month can vary between 28, 29, 30, or 31 days.
  - A year can be 365 or 366 days (leap years).
- In contrast, time units such as seconds, minutes, and hours are fixed. For instance, there are always 60 seconds in a minute and 60 minutes in an hour.

**Example:**  
Adding 1 calendar month to January 31 may result in February 28 (or 29 in a leap year) rather than February 31, which does not exist.

## 2. Conceptual Differences Between Calendar and Time Units
- **Calendar units** are positional and relate to transitions within a calendar system. For example, moving from "December 31 to January 1" indicates crossing into a new day, even if only 1 second has passed.
- **Time units** measure exact durations, such as the total number of seconds, minutes, or hours between two timestamps.

**Example:**  
The difference between `2012-12-31T23:59:59Z` and `2013-01-01T00:59:59Z`:
- In **calendar terms**, this spans 2 calendar days, as moving even 1 second into January 1 is considered a new day.
- In **time units**, the difference is precisely 1 hour or 60 minutes.

## 3. Risks of Mixing Units
- Mixing calendar and time units can lead to misleading interpretations:
  - Phrases like "1 day and 2 hours" might be ambiguous if not explicitly tied to a specific time context.
  - A span of "24 hours" does not always equate to "1 calendar day," particularly when factors like daylight saving time come into play.

## When to Use Each Type of Arithmetic
- Use **calendar units** when dealing with schedules, recurring events, or positional changes within a date system (e.g., adding months to calculate an anniversary).
- Use **time units** when working with precise durations, such as timers, interval measurements, or elapsed time calculations.
